### PR TITLE
Add entry point

### PR DESCRIPTION
**Pull request by ocefpaf**
Some updates, re-add the license file, and add the entrypoints.

@CJ-Wright and @jasongrout why was the license file removed? Was there any issue that I missed?

### CODE REVIEW

**Comment by jasongrout** [comment]
I don't know why the license file isn't there.

**Comment by ocefpaf** [comment]
> I don't know why the license file isn't there.

I asked b/c you removed it here: https://github.com/conda-forge/recommonmark-feedstock/pull/1/commits/2eecdd66693a798a6646410d0850e98cbd20f5f8

**Comment by jasongrout** [comment]
Looks like there was an error before? Is the license file distributed now?

**Comment by jasongrout** [comment]
See the comment I left in the recipe and the commit message...

**Comment by ocefpaf** [comment]
> See the comment I left in the recipe and the commit message...

I did. It did not make sense though b/c it was passing before and it is passing now with the license there :-/

I'll check the package to see if things are OK.

**Comment by jasongrout** [comment]
> I'll check the package to see if things are OK.

Great! I'm starting to remember dealing with something odd with the license, but I'll defer to whatever my past self said in a comment. If it works now, then great!

**Pull request merged**
